
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xef\x02\xc6\x823\x8e<\x9c\xfe\xf2\xbf\xb3jH\x0b^'
    
_lr_action_items = {'H2':([0,12,],[2,2,]),'H3':([0,12,],[3,3,]),'H1':([0,12,],[4,4,]),'TEXT':([0,2,3,4,12,],[5,5,5,5,5,]),'CR':([5,6,7,8,9,10,11,13,],[-8,12,-7,-2,-5,-6,-4,-3,]),'$end':([1,5,6,7,8,9,10,11,13,],[0,-8,-1,-7,-2,-5,-6,-4,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'body':([0,],[1,]),'expression':([0,12,],[8,13,]),'statement':([0,],[6,]),'factor':([0,2,3,4,12,],[7,9,10,11,7,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> body","S'",1,None,None,None),
  ('body -> statement','body',1,'p_body','run.py',46),
  ('statement -> expression','statement',1,'p_state','run.py',50),
  ('statement -> statement CR expression','statement',3,'p_state','run.py',51),
  ('expression -> H1 factor','expression',2,'p_exp_cr','run.py',58),
  ('expression -> H2 factor','expression',2,'p_exp_cr','run.py',59),
  ('expression -> H3 factor','expression',2,'p_exp_cr','run.py',60),
  ('expression -> factor','expression',1,'p_exp_cr','run.py',61),
  ('factor -> TEXT','factor',1,'p_factor_text','run.py',74),
]
